version: '2'
services:
  tidyverse:
    container_name: RStudio-tidyverse
    restart: unless-stopped
    environment:
      - PASSWORD=spagnolilab
    ports:
      - '9119:8787'
    image: rocker/tidyverse
    volumes:
      - /home/pranav/work:/home/rstudio/workspace/work
      - /home/pranav/.ssh/id_ed25519:/home/rstudio/.ssh/id_ed25519:ro