version: '2'

networks:
  default:
    driver: bridge

services:
  genomics-studio:
    container_name: Genomics-Studio
    image: pranavmishra90/genomics-studio-base:latest
    restart: unless-stopped
    environment:
      - PASSWORD=$PASSWORD
    networks:
      - default
    ports:
      - '9119:8787'
    volumes:
      - /home/pranav/work:/home/rstudio/workspace/work
